image: gcc

stages:
    - build

build:linux:
    stage: build
    tags:
      - linux
    
    before_script:
    - apt update && apt -y install cmake

    script:
        - mkdir build && cd build/
        - cmake ..
        - cmake --build .
        - ./myproject
        - echo ${pwd}
