# Имя 
name: Docker Image CI

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file Dockerfile --tag hello_cmake
    - name: Run docker container
      run: docker run --name my_container hello_cmake 
